# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7f7443f81a6891ecd05470f465b0fa6e5cf0201e60da82c50ec45a8357b8e383bb7787ce98499c0d9fdc6f4e3bef80beeb40f8e444b8da39b221cbf8b8d343

test:
  secret_key_base: cdcb7c10a14c47e6faf69300ba41ec207ead0f09cc42467155ed9a7a5eee87a74498dd4056fa1937ec06d14c71b2d3c21f3fd497d08265ef9ff68d630d48f83f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
